version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: oruma_user
      POSTGRES_PASSWORD: oruma_password
      POSTGRES_DB: oruma_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oruma_user -d oruma_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  backend:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://oruma_user:oruma_password@db:5432/oruma_db
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET_KEY: your-super-secret-key-change-in-production
      API_DEBUG: "true"
      CORS_ORIGINS: '["http://localhost:5173","http://localhost:3000"]'
    volumes:
      - ./uploads:/app/uploads
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 3333 --reload

volumes:
  postgres_data:
  redis_data: